### ISSUE TITLE
"Poly null of" error if next centroid is very close

### ISSUE THREAD

**Issue by saturnanwalt** [ArlindNocaj/power-voronoi-diagram#3]
Hi,

I know the insertion of duplicate sites/voronoi centroids is not supported and will lead to NullPointerExceptions when trying to access the Polygon of the duplicate site via duplSite.getPolygon().

Nevertheless, I get the same error when there are some sites/voronoi centroids very close to each other. The errors seem to occur when the distance between two sites is smaller than 2.0E-4. 

Here are some system.out.printlns, where I am writing information about the site with a null polygon and their closest site/voronoi centroids to the console:

(This is from a VoronoiDiagram with 40k sites)

-----
site_37314 [359.880278;51.5033]
no duplicate was found
closest distance for site[359.880278;51.5033]: 1.3800000306218863E-4
closestSite for site_37314 [359.880416;51.5033]
///////////////////////
site_38144 [-355.11748;52.3692]
no duplicate was found
closest distance for site[-355.11748;52.3692]: 1.4142136205919087E-4
closestSite for site_38144 [-355.11758;52.3691]
///////////////////////
site_38856 [-224.215;34.9946]
no duplicate was found
closest distance for site[-224.215;34.9946]: 1.9999999494757503E-4
closestSite for site_38856 [-224.215;34.9948]

-----

Is there any chance for a fix? It wouldn't even be that much of a problem if I could access the neighbors of the specified site, but unfortunately the methods site.getNeighbors() and site.getOldNeighbors() also return null.

**Comment by saturnanwalt** [comment]
Hi,

I've tried a workaround with multiplying the coordinates with some constant factor (between 10 and 10.000), and so far it looks quit promising. Yet, there is some strange behaviour to be observed.

Generally, two errors can occur:

- The 'null polygon' error i've mentioned in my first post, when two sites/voronoi centers are too close to each other.

- A RuntimeException when the scaling for the coordinates is too big. Stack trace:
java.lang.RuntimeException: Twin of Edge is NULL. Cannot Connect Edges!
java.lang.RuntimeException: Twin of Edge is NULL. Cannot Connect Edges!
	at kn.uni.voronoitreemap.convexHull.JFace.link(JFace.java:130)
	at kn.uni.voronoitreemap.convexHull.JConvexHull.compute(JConvexHull.java:105)

Since these errors can occur, I'm looping with different multipliers and recompute the diagram until none of both errors occur. Strangely, the computation of the Voronoi diagram is non-deterministic. Depending on how many loops I have performed before, the computation of the Voronoi diagram succeeds or fails for the multiplier 1000. Here some sysouts for illustration:

- (Success, run1):
null polygon: -52.3587;575.827
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 10.0)
null polygon: 35819.773;5306.49
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 100.0)
**Everything ok: 359868.76999999996;51516.3
Final multiplier for scaling of coordinates: 1000.0**

- (Failure, run2):
null polygon: -4.09443;57.5617
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 1.0)
null polygon: 3559.0543000000002;575.617
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 10.0)
null polygon: 35638.917;5523.32
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 100.0)
**null polygon: 359868.76999999996;51516.3
Error while accessing the site polygons. Recomputing VD with readjusted parameter scaling...(oldValue: 1000.0)**
Error while computing the voronoi diagram. Recomputing VD with readjusted parameter scaling...(oldValue: 10000.0)
Final multiplier for scaling of coordinates: 2000

As you can see, the sites which produce the NullPolygon-Errors differ between the runs, even though the inserted data is the same. Additionally, in each run, the PowerDiagram itself, the root polygon and the sites are completely new initialized objects before computing the diagram. 

Hence, I wonder why there are these differences. Do you use some kind of randomization for computing the diagrams (the above shown runs are replicable, though)? Or is there some static data which does not get resetted when computing a new diagram?

Best regards,
saturnanwal

**Comment by ArlindNocaj** [comment]
Unfortunately there is a limit of precision when using doubles for computation geometry decisions.

If the double precision does not allow for correct geometric decision, e.g., whether a point is on the left or right side of a line, then there is no easy way of fixing it. Have a look on CGAL if you need higher precision. 

As you already noticed you can shift this problem a bit if you for example make sure that the resulting values do not get too large or too small, e.g., by scaling or centering the points to the origin.

The used algorithm to determine the convex hull  (which is required for the Power diagram) is randomized on purpose for better performance. If you want to deactivate that just use a seed for the random number generators.

**Comment by saturnanwalt** [comment]
Thank you very much for your response.

Where exactly are these random number generators you are talking of located? In the class for computing the convex hull, there is a Random object, but it already gets initialized with some seed:

protected final Random rand = new Random(1985);

Or would I have to create a new Random within the permutation() method?

Best regards,
saturnanwalt

**Comment by saturnanwalt** [comment]
There were some static Randoms in several classes. After removing the static modifier, the problems seem gone. Here are the classes where I removed the static modifier from the respective Randoms:

- OpenList
- JSite
- PowerDiagram
